minimumReleaseAge: 144000
overrides:
  form-data@<2.5.4: '>=2.5.4'
  form-data@>=4.0.0 <4.0.4: '>=4.0.4'
  qs@<6.14.1: '>=6.14.1'
  tough-cookie@<4.1.3: '>=4.1.3'

auditConfig:
  ignoreCves:
    - CVE-2023-28155 # the request package used is no longer maintained
